# Predective Analytics

In [1]:
from pandas import read_csv
from numpy import set_printoptions

In [2]:
filename = 'BBC.csv'
dataframe = read_csv(filename) 

In [3]:
df = read_csv('BBC.csv')

In [4]:
dataframe.tail(10)

MaritalStatus  Gender  YearlyIncome  TotalChildren  \
18474              3       1         20000              2   
18475              3       1         20000              2   
18476              3       2         20000              2   
18477              3       1         20000              2   
18478              4       1         30000              3   
18479              4       1         30000              1   
18480              4       2         30000              3   
18481              4       1         30000              3   
18482              5       1         30000              3   
18483              5       1         30000              0   

       NumberChildrenAtHome  EnglishEducation  HouseOwnerFlag  \
18474                     0                 3               0   
18475                     0                 3               0   
18476                     0                 3               0   
18477                     0                 3               0   
18478                     0                 4               1   
18479                     0                 4               1   
18480                     0                 4               1   
18481                     0                 4               0   
18482                     0                 5               1   
18483                     0                 5               1   

       NumberCarsOwned  CommuteDistance  Region  Age  BikeBuyer  
18474                1                1       3   57          1  
18475                1                5       3   57          1  
18476                1                1       3   57          1  
18477                1                2       3   57          1  
18478                0                1       3   57          1  
18479                0                1       3   58          1  
18480                0                1       3   56          1  
18481                0                1       3   57          1  
18482                0                1       3   58          1  
18483                0                1       3   57          1

In [5]:
dataframe.head(10)

MaritalStatus  Gender  YearlyIncome  TotalChildren  NumberChildrenAtHome  \
0              5       1         90000              2                     0   
1              5       1         60000              3                     3   
2              5       1         60000              3                     3   
3              5       2         70000              0                     0   
4              5       2         80000              5                     5   
5              5       1         70000              0                     0   
6              5       2         70000              0                     0   
7              5       1         60000              3                     3   
8              5       2         60000              4                     4   
9              5       1         70000              0                     0   

   EnglishEducation  HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region  \
0                 5               1                0                2       2   
1                 5               0                1                1       2   
2                 5               1                1                5       2   
3                 5               0                1               10       2   
4                 5               1                4                2       2   
5                 5               1                1               10       2   
6                 5               1                1               10       2   
7                 5               1                2                1       2   
8                 5               1                3               20       2   
9                 5               0                1               10       2   

   Age  BikeBuyer  
0   50          1  
1   51          1  
2   51          1  
3   49          1  
4   48          1  
5   51          1  
6   51          1  
7   52          1  
8   52          1  
9   52          1

In [6]:
dataframe.shape

(18484, 12)

In [7]:
dataframe.describe()

MaritalStatus        Gender   YearlyIncome  TotalChildren  \
count   18484.000000  18484.000000   18484.000000   18484.000000   
mean        3.310106      1.494103   57305.777970       1.844352   
std         1.426147      0.499979   32285.841703       1.612408   
min         1.000000      1.000000   10000.000000       0.000000   
25%         2.000000      1.000000   30000.000000       0.000000   
50%         3.000000      1.000000   60000.000000       2.000000   
75%         5.000000      2.000000   70000.000000       3.000000   
max         5.000000      2.000000  170000.000000       5.000000   

       NumberChildrenAtHome  EnglishEducation  HouseOwnerFlag  \
count          18484.000000      18484.000000    18484.000000   
mean               1.004058          3.310106        0.676369   
std                1.522660          1.426147        0.467874   
min                0.000000          1.000000        0.000000   
25%                0.000000          2.000000        0.000000   
50%                0.000000          3.000000        1.000000   
75%                2.000000          5.000000        1.000000   
max                5.000000          5.000000        1.000000   

       NumberCarsOwned  CommuteDistance        Region           Age  \
count     18484.000000     18484.000000  18484.000000  18484.000000   
mean          1.502705         6.003246      1.789710     54.603928   
std           1.138394         6.382562      0.872664     11.255252   
min           0.000000         1.000000      1.000000     36.000000   
25%           1.000000         1.000000      1.000000     46.000000   
50%           2.000000         2.000000      1.000000     53.000000   
75%           2.000000        10.000000      3.000000     62.000000   
max           4.000000        20.000000      3.000000    106.000000   

          BikeBuyer  
count  18484.000000  
mean       0.494049  
std        0.499978  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        1.000000  
max        1.000000

In [8]:
dataframe.values

array([[    5,     1, 90000, ...,     2,    50,     1],
       [    5,     1, 60000, ...,     2,    51,     1],
       [    5,     1, 60000, ...,     2,    51,     1],
       ...,
       [    4,     1, 30000, ...,     3,    57,     1],
       [    5,     1, 30000, ...,     3,    58,     1],
       [    5,     1, 30000, ...,     3,    57,     1]])

In [9]:
array = dataframe.values

In [13]:
X = array[:,0:11] 
Y = array[:,11]

print(X)
print(Y)

[[    5     1 90000 ...     2     2    50]
 [    5     1 60000 ...     1     2    51]
 [    5     1 60000 ...     5     2    51]
 ...
 [    4     1 30000 ...     1     3    57]
 [    5     1 30000 ...     1     3    58]
 [    5     1 30000 ...     1     3    57]]
[1 1 1 ... 1 1 1]


In [14]:
print(dataframe.groupby('BikeBuyer').size())

BikeBuyer
0    9352
1    9132
dtype: int64


In [15]:
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC

In [16]:
! echo "# PredectiveLearningBasics" >> README.md

In [17]:
! git init

Initialized empty Git repository in /Users/nvrsettle/BDAPython /.git/


In [18]:
! git add README.md

In [19]:
! git add .

In [20]:
! git commit -m "first commit"

[master (root-commit) 75cf371] first commit
 Committer: Saikiran Sondarkar <nvrsettle@users-MacBook-Air.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 8 files changed, 24408 insertions(+)
 create mode 100644 .ipynb_checkpoints/A Gentle Intro to SKLearn-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/PredectiveAnalytics-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/Python Basics-checkpoint.ipynb
 create mode 100644 A Gentle Intro to SKLearn.ipynb
 create mode 100644 BBC.csv
 create mode 100644 PredectiveAnalytics.ipynb
 create mode 100644 Python Basics.ipynb
 create mode 100644 RE

In [22]:
! git remote add origin https://github.com/sai-sondarkar/PredectiveLearningBasics.git

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sai-sondarkar/PredectiveLearningBasics.git/'
